/**
 * Construction-specific metric catalog template
 */
export const CONSTRUCTION_METRIC_CATALOG = [
  {
    key: 'backlog_total',
    name: 'Total Backlog',
    description: 'Total value of all active projects',
    formula: 'SUM(projects.contract_value) WHERE status IN (PLANNING, ACTIVE)',
    source: 'Construction Projects',
    cadence: 'Weekly',
  },
  {
    key: 'backlog_by_status',
    name: 'Backlog by Status',
    description: 'Backlog value broken down by project status',
    formula: 'SUM(projects.contract_value) GROUP BY status',
    source: 'Construction Projects',
    cadence: 'Weekly',
  },
  {
    key: 'wip_earned_vs_billed',
    name: 'WIP: Earned vs Billed',
    description: 'Work in progress - earned value minus billed amount',
    formula: 'SUM(job_cost_snapshots.earned_value) - SUM(invoices.amount WHERE status IN (SENT, PAID))',
    source: 'Job Cost Snapshots, Invoices',
    cadence: 'Weekly',
  },
  {
    key: 'gross_margin_pct',
    name: 'Gross Margin %',
    description: 'Portfolio gross margin percentage (revenue - cost) / revenue',
    formula: '(SUM(invoices.amount) - SUM(job_cost_snapshots.actual_cost)) / SUM(invoices.amount)',
    source: 'Invoices, Job Cost Snapshots',
    cadence: 'Weekly',
  },
  {
    key: 'project_margin_pct',
    name: 'Project Margin %',
    description: 'Individual project margin percentage',
    formula: '(project_revenue - project_cost) / project_revenue',
    source: 'Job Cost Snapshots, Invoices',
    cadence: 'Weekly',
  },
  {
    key: 'budget_vs_actual_variance',
    name: 'Budget vs Actual Variance',
    description: 'Percentage variance between budget and actual costs',
    formula: '((actual_cost - budget) / budget) * 100',
    source: 'Job Cost Snapshots',
    cadence: 'Weekly',
  },
  {
    key: 'cost_to_complete_variance',
    name: 'Cost-to-Complete Variance',
    description: 'Estimated cost to complete vs remaining budget',
    formula: '(estimated_cost_to_complete - remaining_budget) / remaining_budget',
    source: 'Job Cost Snapshots',
    cadence: 'Weekly',
  },
  {
    key: 'change_order_aging_days',
    name: 'Change Order Aging (Days)',
    description: 'Average days pending for change orders',
    formula: 'AVG(CURRENT_DATE - submitted_date) WHERE status = PENDING',
    source: 'Change Orders',
    cadence: 'Weekly',
  },
  {
    key: 'approved_unbilled_change_orders',
    name: 'Approved Unbilled Change Orders ($)',
    description: 'Total dollar value of approved change orders not yet billed',
    formula: 'SUM(amount) WHERE status = APPROVED AND billed_date IS NULL',
    source: 'Change Orders',
    cadence: 'Weekly',
  },
  {
    key: 'schedule_variance_days',
    name: 'Schedule Variance (Days)',
    description: 'Average days ahead/behind baseline schedule',
    formula: 'AVG(forecast_date - baseline_date)',
    source: 'Schedule Milestones',
    cadence: 'Weekly',
  },
  {
    key: 'labor_productivity',
    name: 'Labor Productivity',
    description: 'Hours per unit completed (or vs baseline)',
    formula: 'SUM(hours) / SUM(units_completed)',
    source: 'Labor Entries',
    cadence: 'Weekly',
  },
  {
    key: 'equipment_utilization_pct',
    name: 'Equipment Utilization %',
    description: 'Percentage of equipment hours used vs total available',
    formula: '(SUM(hours_used) / (SUM(hours_used) + SUM(idle_hours))) * 100',
    source: 'Equipment Logs',
    cadence: 'Weekly',
  },
  {
    key: 'ar_over_60_days',
    name: 'AR Over 60 Days',
    description: 'Total accounts receivable balance over 60 days old',
    formula: 'SUM(balance) WHERE (CURRENT_DATE - due_date) > 60',
    source: 'Construction Invoices',
    cadence: 'Weekly',
  },
  {
    key: 'ar_over_90_days',
    name: 'AR Over 90 Days',
    description: 'Total accounts receivable balance over 90 days old',
    formula: 'SUM(balance) WHERE (CURRENT_DATE - due_date) > 90',
    source: 'Construction Invoices',
    cadence: 'Weekly',
  },
  {
    key: 'dso_estimate',
    name: 'DSO Estimate',
    description: 'Days Sales Outstanding - average collection period',
    formula: '(SUM(balance) / AVG(daily_revenue)) * 30',
    source: 'Construction Invoices',
    cadence: 'Weekly',
  },
  {
    key: 'cash_risk_score',
    name: 'Cash Risk Score',
    description: 'Composite score based on AR aging, margin, and schedule variance',
    formula: 'Composite: (ar_over_90_pct * 0.4) + (margin_variance * 0.3) + (schedule_variance_pct * 0.3)',
    source: 'Multiple',
    cadence: 'Weekly',
  },
  {
    key: 'safety_incidents',
    name: 'Safety Incidents',
    description: 'Number of safety incidents (placeholder if no data)',
    formula: 'COUNT(*) WHERE incident_type IS NOT NULL',
    source: 'Safety Logs (placeholder)',
    cadence: 'Weekly',
  },
]

/**
 * Construction alert rules
 */
export const CONSTRUCTION_ALERT_RULES = [
  {
    key: 'margin_drop_below_threshold',
    name: 'Margin Drop Below Threshold',
    description: 'Project margin drops below threshold (default 10%)',
    trigger: 'project_margin_pct < threshold',
    severity: 'high',
  },
  {
    key: 'cost_variance_high',
    name: 'Cost Variance > X%',
    description: 'Budget vs actual variance exceeds threshold (default 15%)',
    trigger: 'ABS(budget_vs_actual_variance) > threshold',
    severity: 'high',
  },
  {
    key: 'pending_change_orders_aging',
    name: 'Pending Change Orders Aging',
    description: 'Change orders pending longer than threshold (default 30 days)',
    trigger: 'change_order_aging_days > threshold',
    severity: 'medium',
  },
  {
    key: 'approved_change_orders_not_billed',
    name: 'Approved Change Orders Not Billed',
    description: 'Approved change orders not billed within threshold (default 14 days)',
    trigger: 'approved_date IS NOT NULL AND billed_date IS NULL AND (CURRENT_DATE - approved_date) > threshold',
    severity: 'medium',
  },
  {
    key: 'schedule_slip',
    name: 'Schedule Slip',
    description: 'Milestone schedule slip exceeds threshold (default 7 days)',
    trigger: 'schedule_variance_days < -threshold',
    severity: 'high',
  },
  {
    key: 'labor_productivity_low',
    name: 'Labor Productivity Below Threshold',
    description: 'Labor productivity below threshold for 2 consecutive weeks',
    trigger: 'labor_productivity < baseline * threshold AND consecutive_weeks >= 2',
    severity: 'medium',
  },
  {
    key: 'equipment_idle',
    name: 'Equipment Idle Hours',
    description: 'Equipment idle hours exceed threshold per week (default 20 hours)',
    trigger: 'SUM(idle_hours) > threshold',
    severity: 'low',
  },
  {
    key: 'ar_past_due',
    name: 'AR Invoice Past Due',
    description: 'AR invoices past due beyond threshold (default 60 days) or amount threshold',
    trigger: '(CURRENT_DATE - due_date) > threshold OR balance > amount_threshold',
    severity: 'high',
  },
]


