// Real prospect data from compassiq-prospects.md
export interface Prospect {
  id: string
  company: string
  industry: string
  size: string
  location: string
  painPoints: string[]
  status: 'research' | 'outreach' | 'call-scheduled' | 'proposal' | 'won' | 'lost'
  estimatedValue: number
  priority: 'high' | 'medium' | 'low'
  lastContact?: string
  nextAction?: string
  notes?: string
  emailsSent?: number
  responses?: number
}

export const prospects: Prospect[] = [
  {
    id: 'nick-s-air-conditioning',
    company: 'Nick\'s Air Conditioning',
    industry: 'HVAC',
    size: '20-50',
    location: 'Houston, TX',
    painPoints: ["Basic chat but limited portal features","High service volume (200+ apartment management)"],
    status: 'research',
    estimatedValue: 36000,
    priority: 'high',
    notes: 'Family-owned, 40+ years, handles both residential and commercial (200+ apartment homes). Has basic tech (webchat) but likely needs operations intelligence.'
  },
  {
    id: 'lee-thompson-co',
    company: 'Lee Thompson Co',
    industry: 'HVAC',
    size: '30-75',
    location: 'Houston, TX',
    painPoints: ["No visible portal or advanced scheduling","Legacy system likely","Likely manual dispatch"],
    status: 'research',
    estimatedValue: 34000,
    priority: 'medium',
    notes: '63 years in business, established reputation, likely using legacy systems. Good size fit but limited contact info.'
  },
  {
    id: 'nick-s-plumbing-services',
    company: 'Nick\'s Plumbing Services',
    industry: 'Plumbing',
    size: '40-100',
    location: 'Houston, TX',
    painPoints: ["Has basics, lacks intelligence layer","Managing residential + commercial","Possible in dispatch"],
    status: 'research',
    estimatedValue: 37500,
    priority: 'high',
    notes: 'Family-owned since 1979, has VIP program and financing. Growing into HVAC services. Good candidate - has basic tech but needs intelligence.'
  },
  {
    id: 'santhoff-plumbing-company',
    company: 'Santhoff Plumbing Company',
    industry: 'Plumbing',
    size: '50-120',
    location: 'Missouri City (Houston area), TX',
    painPoints: ["Has club program but lacks ops analytics","Managing 12,000+ service calls","Likely dispatch coordination"],
    status: 'research',
    estimatedValue: 39000,
    priority: 'high',
    notes: 'Veteran-owned, 50 years, serves 12,000+ homes/businesses. Strong candidate with membership program but needs intelligence tools.'
  },
  {
    id: 'preventive-pest-control',
    company: 'Preventive Pest Control',
    industry: 'Pest Control',
    size: '15-40',
    location: 'Houston, TX',
    painPoints: ["Has scheduling, lacks route intelligence","Quarterly service coordination","Route optimization needs"],
    status: 'research',
    estimatedValue: 37000,
    priority: 'high',
    notes: 'Nearly 20 years, has online booking. Perfect size (15-40 employees). Needs route optimization for quarterly services.'
  },
  {
    id: 'hartz-pest-control',
    company: 'Hartz Pest Control',
    industry: 'Pest Control',
    size: '20-50',
    location: 'Houston, TX',
    painPoints: ["Has programs but lacks analytics","Quarterly service management","Technician routing"],
    status: 'research',
    estimatedValue: 38000,
    priority: 'high',
    notes: 'Family-owned since 1989, 35+ years. Has service programs, needs route intelligence. Strong testimonials.'
  },
  {
    id: 'cypress-creek-pest-control',
    company: 'Cypress Creek Pest Control',
    industry: 'Pest Control',
    size: '30-80',
    location: 'Houston, TX',
    painPoints: ["Legacy systems probable","12,000+ locations to manage","Likely significant"],
    status: 'research',
    estimatedValue: 40500,
    priority: 'high',
    notes: '56 years in business, one of largest independent pest control in Texas. 12,000+ customers. HIGH NEED for operations intelligence.'
  },
  {
    id: 'e3-electric',
    company: 'E3 Electric',
    industry: 'Electrical',
    size: '15-35',
    location: 'Houston, TX',
    painPoints: ["Basic setup, needs intelligence","Emergency + planned work balance","Dispatch coordination"],
    status: 'research',
    estimatedValue: 35000,
    priority: 'high',
    notes: '21 years, detail-oriented. Good size. Maintenance programs indicate growth readiness.'
  },
  {
    id: 'jon-wayne-services',
    company: 'Jon Wayne Services',
    industry: 'Multi-Service (HVAC/Plumbing/Electrical)',
    size: '50-150',
    location: 'San Antonio, TX',
    painPoints: ["Multi-trade complexity","Managing 4 service lines","Cross-service coordination"],
    status: 'research',
    estimatedValue: 38500,
    priority: 'high',
    notes: 'Multi-service company (HVAC/Plumbing/Electrical). Complex operations = high need for intelligence.'
  },
  {
    id: 'champion-home-services',
    company: 'Champion Home Services',
    industry: 'Multi-Service (HVAC/Plumbing/Electrical)',
    size: '40-100',
    location: 'San Antonio, TX',
    painPoints: ["Basic scheduling","Residential + commercial","Multi-trade dispatching"],
    status: 'research',
    estimatedValue: 36500,
    priority: 'high',
    notes: 'Since 2007, multi-service, awards. Complex operations need intelligence tools.'
  },
  {
    id: 'blue-science-pools',
    company: 'Blue Science Pools',
    industry: 'Pool Service',
    size: '80-200',
    location: 'Multiple (Dallas, Houston, Austin, San Antonio), TX',
    painPoints: ["Weekly scheduling complexity","Multi-location coordination","Route optimization across 4 regions"],
    status: 'research',
    estimatedValue: 42000,
    priority: 'high',
    notes: 'Family-owned, operates in 4 major TX metros. HIGH COMPLEXITY. Perfect candidate for route/ops intelligence.'
  },
  {
    id: 'romney-pest-control',
    company: 'Romney Pest Control',
    industry: 'Pest Control',
    size: '30-80',
    location: 'Multiple (Dallas, Houston, Austin, San Antonio), TX',
    painPoints: ["Route coordination","Same-day service promise","Multi-location dispatch"],
    status: 'research',
    estimatedValue: 39500,
    priority: 'high',
    notes: '10+ years, 4 major metros, same-day service. Multi-location complexity + speed promise = high need.'
  },
  {
    id: 'rescue-air-and-plumbing',
    company: 'Rescue Air and Plumbing',
    industry: 'HVAC/Plumbing',
    size: '15-40',
    location: 'Dallas, TX',
    painPoints: ["Operations visibility gaps","Manual dispatch processes"],
    status: 'research',
    estimatedValue: 32500,
    priority: 'medium',
    notes: 'Top-rated on Yelp. Need website visit for full assessment.'
  },
  {
    id: 'texas-ace-service',
    company: 'Texas Ace Service',
    industry: 'HVAC',
    size: '10-30',
    location: 'Dallas-Fort Worth, TX',
    painPoints: ["Likely"],
    status: 'research',
    estimatedValue: 31000,
    priority: 'medium',
    notes: 'Smaller operation, needs full assessment.'
  },
  {
    id: 'baker-brothers-plumbing',
    company: 'Baker Brothers Plumbing',
    industry: 'Plumbing/HVAC',
    size: '60-150',
    location: 'Dallas, TX',
    painPoints: ["Likely present","Large service area","Multi-trade coordination"],
    status: 'research',
    estimatedValue: 35500,
    priority: 'high',
    notes: 'Established DFW plumbing/HVAC. Multi-service complexity.'
  },
  {
    id: 'abacus-plumbing-air-conditioning-electrical',
    company: 'Abacus Plumbing Air Conditioning & Electrical',
    industry: 'Multi-Service (Plumbing/HVAC/Electrical)',
    size: '80-200',
    location: 'Austin, TX',
    painPoints: ["Coordination complexity","3 service lines","Multi-trade dispatch"],
    status: 'research',
    estimatedValue: 38000,
    priority: 'high',
    notes: 'Since 2003, comprehensive home services. Multi-trade = high ops complexity.'
  },
  {
    id: 'fox-service-company',
    company: 'Fox Service Company',
    industry: 'Multi-Service (HVAC/Plumbing/Electrical)',
    size: '60-150',
    location: 'Austin, TX',
    painPoints: ["Older company needing modernization","Multi-service coordination","Legacy systems likely"],
    status: 'research',
    estimatedValue: 39500,
    priority: 'high',
    notes: '52 years serving Austin. Multi-service. Likely using legacy systems - PERFECT for modernization.'
  },
  {
    id: 'salt-service-co-plumbing-air-electric',
    company: 'SALT Service Co (Plumbing Air & Electric)',
    industry: 'Multi-Service (Plumbing/HVAC)',
    size: '40-100',
    location: 'Austin, TX',
    painPoints: ["Has basics, needs intelligence","Plumbing + HVAC coordination","Possible"],
    status: 'research',
    estimatedValue: 37000,
    priority: 'high',
    notes: 'Born in Austin 1984, family-run. Has TuneUp program. Good candidate.'
  },
  {
    id: 'green-leaf-air',
    company: 'Green Leaf Air',
    industry: 'HVAC',
    size: '20-60',
    location: 'Richardson (Dallas area), TX',
    painPoints: ["Multi-region coverage","Likely"],
    status: 'research',
    estimatedValue: 36000,
    priority: 'high',
    notes: '15+ years, serving multiple metros. Good size, needs assessment.'
  },
  {
    id: 'team-enoch-electric-plumbing-air-roofing',
    company: 'Team Enoch (Electric, Plumbing, Air, Roofing)',
    industry: 'Multi-Service (HVAC/Plumbing/Electrical/Roofing)',
    size: '40-100',
    location: 'Fort Worth/Arlington, TX',
    painPoints: ["High complexity","Managing 4 distinct service lines","4-service coordination"],
    status: 'research',
    estimatedValue: 40000,
    priority: 'high',
    notes: '4 service lines (HVAC/Plumbing/Electrical/Roofing). VERY high ops complexity. Excellent candidate.'
  },
  {
    id: 'h-town-ac-and-plumbing',
    company: 'H-Town AC And Plumbing',
    industry: 'HVAC/Plumbing',
    size: '15-45',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35000,
    priority: 'high',
    notes: 'Top-rated Houston HVAC/Plumbing combo'
  },
  {
    id: 'richmond-s-air',
    company: 'Richmond\'s Air',
    industry: 'HVAC',
    size: '20-60',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36500,
    priority: 'high',
    notes: 'Since 2002, full-service HVAC'
  },
  {
    id: 'heights-a-c-heating',
    company: 'Heights A/C & Heating',
    industry: 'HVAC',
    size: '10-35',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 34000,
    priority: 'medium',
    notes: 'Local Heights area specialist'
  },
  {
    id: 'smart-air-houston',
    company: 'Smart Air Houston',
    industry: 'HVAC',
    size: '15-40',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35500,
    priority: 'high',
    notes: 'Family-owned Houston area'
  },
  {
    id: 'houk-ac-houston',
    company: 'Houk AC Houston',
    industry: 'HVAC',
    size: '40-100',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37500,
    priority: 'high',
    notes: 'Multi-region HVAC provider'
  },
  {
    id: 'ars-air-conditioning-houston',
    company: 'ARS Air Conditioning Houston',
    industry: 'HVAC/Plumbing',
    size: '100-250',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 32500,
    priority: 'medium',
    notes: 'Larger operation - may be too big'
  },
  {
    id: 'abacus-plumbing-houston',
    company: 'Abacus Plumbing Houston',
    industry: 'Plumbing',
    size: '80-200',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35000,
    priority: 'high',
    notes: 'Large established plumbing company'
  },
  {
    id: 'power-plumbing-houston',
    company: 'Power Plumbing Houston',
    industry: 'Plumbing',
    size: '40-100',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36000,
    priority: 'high',
    notes: 'Commercial construction focus'
  },
  {
    id: 'aaa-plumbers-houston',
    company: 'AAA Plumbers Houston',
    industry: 'Plumbing',
    size: '20-60',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 34500,
    priority: 'medium',
    notes: 'Commercial plumbing specialist'
  },
  {
    id: 'h-town-plumbers',
    company: 'H-Town Plumbers',
    industry: 'Plumbing',
    size: '10-30',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35500,
    priority: 'high',
    notes: 'Top-rated local plumbing'
  },
  {
    id: 'strutton-plumbing-company',
    company: 'Strutton Plumbing Company',
    industry: 'Plumbing',
    size: '25-70',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36500,
    priority: 'high',
    notes: 'Commercial/residential construction'
  },
  {
    id: 'belknap-plumbing',
    company: 'Belknap Plumbing',
    industry: 'Plumbing',
    size: '20-50',
    location: 'Cypress/Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37500,
    priority: 'high',
    notes: 'Trusted 25+ years, Cypress area'
  },
  {
    id: 'david-hicks-plumbing',
    company: 'David Hicks Plumbing',
    industry: 'Plumbing',
    size: '15-40',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35000,
    priority: 'high',
    notes: 'Family-owned residential/commercial'
  },
  {
    id: 'colwell-electric',
    company: 'Colwell Electric',
    industry: 'Electrical',
    size: '25-75',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 38500,
    priority: 'high',
    notes: 'Second-generation family, 30+ years'
  },
  {
    id: 'on-time-electric-houston',
    company: 'On Time Electric Houston',
    industry: 'Electrical',
    size: '15-45',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36000,
    priority: 'high',
    notes: '24 years residential/commercial'
  },
  {
    id: 'pieper-houston-electric',
    company: 'Pieper-Houston Electric',
    industry: 'Electrical',
    size: '30-80',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 39000,
    priority: 'high',
    notes: 'Since 1958, commercial electrical leader'
  },
  {
    id: 'highlights-electrical',
    company: 'Highlights Electrical',
    industry: 'Electrical',
    size: '20-50',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35000,
    priority: 'high',
    notes: 'Commercial electrical & lighting'
  },
  {
    id: 'sandstorm-electrical-llc',
    company: 'Sandstorm Electrical LLC',
    industry: 'Electrical',
    size: '10-35',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 34000,
    priority: 'medium',
    notes: 'State-certified, new construction focus'
  },
  {
    id: 'modern-pest-control-houston',
    company: 'Modern Pest Control Houston',
    industry: 'Pest Control',
    size: '30-80',
    location: 'Houston/Katy, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 41000,
    priority: 'high',
    notes: 'Founded 1952, 70+ years serving Houston'
  },
  {
    id: 'holder-s-pest-solutions',
    company: 'Holder\'s Pest Solutions',
    industry: 'Pest Control',
    size: '25-70',
    location: 'Houston/Galveston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 40000,
    priority: 'high',
    notes: '70+ years, Greater Houston/Galveston'
  },
  {
    id: 'truforce-pest-control',
    company: 'TruForce Pest Control',
    industry: 'Pest Control',
    size: '10-30',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 34500,
    priority: 'medium',
    notes: 'Top-rated Houston pest control'
  },
  {
    id: 'abc-home-commercial-services',
    company: 'ABC Home & Commercial Services',
    industry: 'Multi-Service (Pest/HVAC/Lawn)',
    size: '100-250',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 33000,
    priority: 'medium',
    notes: 'Large multi-service - may be too big'
  },
  {
    id: 'gulf-coast-exterminators',
    company: 'Gulf Coast Exterminators',
    industry: 'Pest Control',
    size: '15-40',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35500,
    priority: 'high',
    notes: 'Family owned, variety of services'
  },
  {
    id: 'rose-roofing-houston',
    company: 'Rose Roofing Houston',
    industry: 'Roofing',
    size: '30-80',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35000,
    priority: 'high',
    notes: 'Quality roofing replacement/repair'
  },
  {
    id: 'moss-roofing-houston',
    company: 'Moss Roofing Houston',
    industry: 'Roofing',
    size: '20-60',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36000,
    priority: 'high',
    notes: 'Residential/commercial roofing leader'
  },
  {
    id: 'joe-ochoa-roofing',
    company: 'Joe Ochoa Roofing',
    industry: 'Roofing',
    size: '25-70',
    location: 'Stafford/Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36500,
    priority: 'high',
    notes: 'Roof leak repair specialists'
  },
  {
    id: 'advanced-roofing-solutions',
    company: 'Advanced Roofing Solutions',
    industry: 'Roofing',
    size: '15-45',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35500,
    priority: 'high',
    notes: 'Inspection, install, repair, replace'
  },
  {
    id: 'braun-s-roofing',
    company: 'Braun\'s Roofing',
    industry: 'Roofing',
    size: '30-80',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 38000,
    priority: 'high',
    notes: '35+ years, A+ BBB rating'
  },
  {
    id: 'jc-c-roofing-company',
    company: 'JC&C Roofing Company',
    industry: 'Roofing',
    size: '20-55',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36000,
    priority: 'high',
    notes: 'Trusted since 2013, financing available'
  },
  {
    id: 'moss-landscaping',
    company: 'Moss Landscaping',
    industry: 'Landscaping',
    size: '30-80',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37000,
    priority: 'high',
    notes: 'Nearly 40 years, white glove service'
  },
  {
    id: 'lightfoot-mechanical',
    company: 'Lightfoot Mechanical',
    industry: 'Multi-Service (HVAC/Plumbing/Electrical)',
    size: '40-100',
    location: 'Fort Worth, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37500,
    priority: 'high',
    notes: 'Multi-service DFW leader'
  },
  {
    id: 'comfort-experts-fort-worth',
    company: 'Comfort Experts Fort Worth',
    industry: 'Multi-Service',
    size: '30-80',
    location: 'Fort Worth, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36500,
    priority: 'high',
    notes: 'HVAC/Plumbing/Electrical combo'
  },
  {
    id: 'service-experts-fort-worth',
    company: 'Service Experts Fort Worth',
    industry: 'HVAC/Plumbing',
    size: '50-120',
    location: 'Fort Worth, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 38500,
    priority: 'high',
    notes: 'Since 1980, 40+ years experience'
  },
  {
    id: 'ages-services-company',
    company: 'AGES Services Company',
    industry: 'HVAC/Electrical',
    size: '20-60',
    location: 'Fort Worth, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35500,
    priority: 'high',
    notes: 'Trusted DFW contractor'
  },
  {
    id: 'berkeys-fort-worth',
    company: 'Berkeys Fort Worth',
    industry: 'Multi-Service',
    size: '40-100',
    location: 'Fort Worth, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37000,
    priority: 'high',
    notes: '24-hour emergency service'
  },
  {
    id: 'a-1-air-dfw',
    company: 'A#1 Air DFW',
    industry: 'Multi-Service',
    size: '30-80',
    location: 'Dallas/Fort Worth, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36000,
    priority: 'high',
    notes: 'AC/Plumbing/Electrical day or night'
  },
  {
    id: 'kahn-mechanical-dfw',
    company: 'Kahn Mechanical DFW',
    industry: 'Commercial HVAC',
    size: '25-70',
    location: 'Dallas/Fort Worth, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36500,
    priority: 'high',
    notes: 'Commercial HVAC + 24/7 emergency'
  },
  {
    id: 'houk-ac-dallas-fort-worth',
    company: 'Houk AC Dallas-Fort Worth',
    industry: 'HVAC',
    size: '50-120',
    location: 'Dallas/Fort Worth, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37000,
    priority: 'high',
    notes: 'Multi-region HVAC specialist'
  },
  {
    id: 'facility-response-group-dallas',
    company: 'Facility Response Group Dallas',
    industry: 'Commercial HVAC',
    size: '30-80',
    location: 'Dallas, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36000,
    priority: 'high',
    notes: 'Commercial HVAC certified techs'
  },
  {
    id: 'service-experts-grand-prairie',
    company: 'Service Experts Grand Prairie',
    industry: 'HVAC/Plumbing',
    size: '35-90',
    location: 'Grand Prairie, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37500,
    priority: 'high',
    notes: 'Formerly Crawford Services, since 2010'
  },
  {
    id: 'efficient-ac-electric-plumbing',
    company: 'Efficient AC Electric Plumbing',
    industry: 'Multi-Service',
    size: '25-70',
    location: 'Austin, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36500,
    priority: 'high',
    notes: 'Quality-driven multi-service'
  },
  {
    id: 'enoch-electric-water-air',
    company: 'Enoch Electric Water & Air',
    industry: 'Multi-Service',
    size: '30-80',
    location: 'Austin, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36000,
    priority: 'high',
    notes: 'Electrical/Plumbing/HVAC combo'
  },
  {
    id: 'blue-diamond-m-e-p',
    company: 'Blue Diamond M.E.P.',
    industry: 'Mechanical/Electrical/Plumbing',
    size: '20-60',
    location: 'Austin, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35500,
    priority: 'high',
    notes: 'M.E.P. services specialist'
  },
  {
    id: 'stan-s-heating-air-plumbing-electric',
    company: 'Stan\'s Heating Air Plumbing Electric',
    industry: 'Multi-Service',
    size: '40-100',
    location: 'Austin, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 39500,
    priority: 'high',
    notes: 'Nearly a century in business'
  },
  {
    id: 'r-r-pest-control-service',
    company: 'R & R Pest Control Service',
    industry: 'Pest Control',
    size: '10-30',
    location: 'Austin/Cedar Park, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35000,
    priority: 'high',
    notes: 'Eco-friendly, family-owned'
  },
  {
    id: 'stride-pest-control',
    company: 'Stride Pest Control',
    industry: 'Pest Control',
    size: '15-45',
    location: 'Round Rock/Austin, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37000,
    priority: 'high',
    notes: '23+ years Austin pest control expert'
  },
  {
    id: 'alta-pest-control',
    company: 'Alta Pest Control',
    industry: 'Pest Control',
    size: '20-60',
    location: 'Round Rock, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35500,
    priority: 'high',
    notes: 'Round Rock and nearby areas'
  },
  {
    id: 'vector-1-pest-control',
    company: 'Vector 1 Pest Control',
    industry: 'Pest Control',
    size: '15-40',
    location: 'Weatherford to Round Rock, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36000,
    priority: 'high',
    notes: 'Central Texas & North Texas coverage'
  },
  {
    id: 'poolie',
    company: 'Poolie',
    industry: 'Pool Service',
    size: '50-120',
    location: 'Austin/Dallas/Houston/San Antonio, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 39000,
    priority: 'high',
    notes: 'Multi-metro pool service leader'
  },
  {
    id: 'texas-pool-services',
    company: 'Texas Pool Services',
    industry: 'Pool Service',
    size: '15-45',
    location: 'Austin, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35500,
    priority: 'high',
    notes: 'Custom pool design/construction'
  },
  {
    id: 'will-fix-it',
    company: 'Will Fix It',
    industry: 'Multi-Service (HVAC/Plumbing)',
    size: '30-80',
    location: 'San Antonio, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36500,
    priority: 'high',
    notes: 'Expert HVAC & plumbing services'
  },
  {
    id: 'aramendia-plumbing-heating-and-air',
    company: 'Aramendia Plumbing Heating and Air',
    industry: 'HVAC/Plumbing',
    size: '35-90',
    location: 'San Antonio, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37000,
    priority: 'high',
    notes: 'Honest straightforward solutions'
  },
  {
    id: 'comfort-air-engineering',
    company: 'Comfort-Air Engineering',
    industry: 'HVAC/Plumbing',
    size: '30-80',
    location: 'San Antonio, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 38500,
    priority: 'high',
    notes: 'Family-owned since 1964'
  },
  {
    id: 'goettl-san-antonio',
    company: 'Goettl San Antonio',
    industry: 'HVAC/Plumbing',
    size: '40-100',
    location: 'San Antonio, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37500,
    priority: 'high',
    notes: 'Deep Texas roots, tight-knit team'
  },
  {
    id: 'evenflow-home-commercial-services',
    company: 'Evenflow Home & Commercial Services',
    industry: 'Multi-Service',
    size: '25-70',
    location: 'San Antonio, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36000,
    priority: 'high',
    notes: 'HVAC/Plumbing/Electrical expert'
  },
  {
    id: 'csw-power-solutions',
    company: 'CSW Power Solutions',
    industry: 'Plumbing/HVAC/Electrical',
    size: '20-55',
    location: 'San Antonio, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36500,
    priority: 'high',
    notes: 'Veteran-owned general contractor'
  },
  {
    id: 'elmer-s-home-services',
    company: 'Elmer\'s Home Services',
    industry: 'HVAC/Plumbing/Electrical',
    size: '30-80',
    location: 'San Antonio, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37000,
    priority: 'high',
    notes: 'Fast reliable 24/7 support'
  },
  {
    id: 'bacon-plumbing-heating-air-electric',
    company: 'Bacon Plumbing Heating Air Electric',
    industry: 'Multi-Service',
    size: '40-100',
    location: 'Plano/Frisco, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37500,
    priority: 'high',
    notes: 'Comprehensive home services Collin County'
  },
  {
    id: 'on-time-experts',
    company: 'On Time Experts',
    industry: 'HVAC/Plumbing',
    size: '30-80',
    location: 'Plano/Allen/McKinney, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36500,
    priority: 'high',
    notes: 'North Dallas communities specialist'
  },
  {
    id: 'astar-dfw',
    company: 'AStar DFW',
    industry: 'Multi-Service',
    size: '25-70',
    location: 'Plano/Irving/Grand Prairie, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36000,
    priority: 'high',
    notes: 'Top-quality multi-service DFW'
  },
  {
    id: 'berkeys-plano',
    company: 'Berkeys Plano',
    industry: 'Multi-Service',
    size: '35-90',
    location: 'Plano, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37000,
    priority: 'high',
    notes: 'Quality affordable service Plano'
  },
  {
    id: 'tempo-air-frisco',
    company: 'Tempo Air Frisco',
    industry: 'HVAC/Plumbing',
    size: '20-60',
    location: 'Frisco, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35500,
    priority: 'high',
    notes: 'AC/HVAC/plumbing specialist'
  },
  {
    id: 'chrome-heating-air',
    company: 'Chrome Heating & Air',
    industry: 'HVAC/Plumbing',
    size: '15-45',
    location: 'Frisco/McKinney/Plano, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35000,
    priority: 'high',
    notes: 'Qualified heating/AC/plumbing techs'
  },
  {
    id: 'hutchins-plumbing-air',
    company: 'Hutchins Plumbing & Air',
    industry: 'Plumbing/HVAC',
    size: '25-70',
    location: 'McKinney, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36000,
    priority: 'high',
    notes: 'Commercial HVAC & plumbing expert'
  },
  {
    id: 'corpest-services',
    company: 'Corpest Services',
    industry: 'Pest Control',
    size: '15-45',
    location: 'Corpus Christi, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36500,
    priority: 'high',
    notes: 'Family-owned since 1994'
  },
  {
    id: 'mathews-ccac',
    company: 'Mathews CCAC',
    industry: 'HVAC/Plumbing/Electrical',
    size: '30-80',
    location: 'Corpus Christi, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37000,
    priority: 'high',
    notes: 'Multi-service Corpus Christi'
  },
  {
    id: 'pete-s-pest-control',
    company: 'Pete\'s Pest Control',
    industry: 'Pest Control',
    size: '10-30',
    location: 'Corpus Christi, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 34500,
    priority: 'medium',
    notes: 'Local pest control specialist'
  },
  {
    id: 'barrett-airworks-service-company',
    company: 'Barrett Airworks Service Company',
    industry: 'HVAC/Plumbing/Electrical',
    size: '25-70',
    location: 'El Paso, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36000,
    priority: 'high',
    notes: 'Expert 24/7 emergency services'
  },
  {
    id: 'innovative-trades-llc',
    company: 'Innovative Trades LLC',
    industry: 'Plumbing/Electrical/HVAC',
    size: '15-45',
    location: 'El Paso, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35000,
    priority: 'high',
    notes: 'One-stop shop El Paso area'
  },
  {
    id: 'dynamic-heating-cooling',
    company: 'Dynamic Heating & Cooling',
    industry: 'HVAC/Electrical/Plumbing/Roofing',
    size: '20-60',
    location: 'El Paso/Las Cruces, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35500,
    priority: 'high',
    notes: 'Multi-service El Paso/NM border'
  },
  {
    id: 'mechanical-technologies-el-paso',
    company: 'Mechanical Technologies El Paso',
    industry: 'HVAC',
    size: '20-55',
    location: 'El Paso, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37500,
    priority: 'high',
    notes: '40+ years dedicated El Paso service'
  },
  {
    id: 'southwest-mechanical-ep',
    company: 'Southwest Mechanical EP',
    industry: 'Commercial HVAC',
    size: '30-80',
    location: 'El Paso, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36500,
    priority: 'high',
    notes: 'Commercial HVAC energy-efficient'
  },
  {
    id: 'scott-heating-cooling',
    company: 'Scott Heating & Cooling',
    industry: 'HVAC',
    size: '15-40',
    location: 'El Paso/Anthony, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35000,
    priority: 'high',
    notes: 'Affordable residential/commercial HVAC'
  },
  {
    id: 'onecall-houston',
    company: 'OneCall Houston',
    industry: 'Multi-Service',
    size: '30-80',
    location: 'The Woodlands, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36500,
    priority: 'high',
    notes: 'Unparalleled HVAC/Plumbing/Electrical'
  },
  {
    id: 'air-tech-of-katy',
    company: 'Air Tech of Katy',
    industry: 'HVAC/Electrical/Plumbing',
    size: '25-70',
    location: 'Katy/The Woodlands, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37000,
    priority: 'high',
    notes: 'Professional multi-service Katy area'
  },
  {
    id: 'red-star-cooling-heating',
    company: 'Red Star Cooling & Heating',
    industry: 'HVAC',
    size: '20-55',
    location: 'The Woodlands, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35500,
    priority: 'high',
    notes: 'Best AC company The Woodlands'
  },
  {
    id: 'the-woodlands-plumbing-air',
    company: 'The Woodlands Plumbing & Air',
    industry: 'Plumbing/HVAC',
    size: '15-45',
    location: 'The Woodlands, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36000,
    priority: 'high',
    notes: 'Locally owned 24/7 availability'
  },
  {
    id: 'airnow-services',
    company: 'AirNow Services',
    industry: 'HVAC',
    size: '20-60',
    location: 'The Woodlands/Magnolia/Tomball, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35500,
    priority: 'high',
    notes: 'Emergency HVAC North Houston area'
  },
  {
    id: 'rocket-city-air-conditioning',
    company: 'Rocket City Air Conditioning',
    industry: 'HVAC',
    size: '25-70',
    location: 'Sugar Land/Katy, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36500,
    priority: 'high',
    notes: 'Greater Houston commercial HVAC'
  },
  {
    id: 'cody-pools',
    company: 'Cody Pools',
    industry: 'Pool Building',
    size: '60-150',
    location: 'Austin/Houston/San Antonio, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 38000,
    priority: 'high',
    notes: 'Nation\'s #1 pool builder multi-metro'
  },
  {
    id: 'patriot-pool-spa',
    company: 'Patriot Pool & Spa',
    industry: 'Pool Service',
    size: '40-100',
    location: 'Austin/Dallas/Fort Worth, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37500,
    priority: 'high',
    notes: 'Fast-growing pool service company'
  },
  {
    id: 'aquapools',
    company: 'AquaPools',
    industry: 'Fiberglass Pools',
    size: '50-120',
    location: 'Multiple TX metros, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37000,
    priority: 'high',
    notes: 'Top pool builder TX/OK/LA'
  },
  {
    id: 'texas-fiberglass-pools',
    company: 'Texas Fiberglass Pools',
    industry: 'Pool Repair/Remodel',
    size: '30-80',
    location: 'Dallas/San Antonio/Austin/Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36500,
    priority: 'high',
    notes: 'Pool repair multi-metro specialist'
  },
  {
    id: 'all-safe-pest-termite',
    company: 'All-Safe Pest & Termite',
    industry: 'Pest Control',
    size: '40-100',
    location: 'Dallas/Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37500,
    priority: 'high',
    notes: 'Trusted pest control DFW & Houston'
  },
  {
    id: 'bugco-pest-control',
    company: 'BUGCO Pest Control',
    industry: 'Pest Control',
    size: '40-100',
    location: 'Houston/Austin/Dallas/San Antonio, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 38500,
    priority: 'high',
    notes: 'Since 2015, multi-metro expansion'
  },
  {
    id: 'perfect-pest-control',
    company: 'Perfect Pest Control',
    industry: 'Commercial Pest Control',
    size: '30-80',
    location: 'Texas & Oklahoma, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 37000,
    priority: 'high',
    notes: '16+ years commercial pest control'
  },
  {
    id: 'green-pest-guys',
    company: 'Green Pest Guys',
    industry: 'Pest Control',
    size: '20-60',
    location: 'Cedar Park/Dallas-McKinney/Spring, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36000,
    priority: 'high',
    notes: 'Eco-friendly since 2010'
  },
  {
    id: 'stampede-pest-control',
    company: 'Stampede Pest Control',
    industry: 'Pest Control',
    size: '25-70',
    location: 'Cypress/McKinney/Dallas/Houston/Austin, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36500,
    priority: 'high',
    notes: 'Effective multi-metro pest control'
  },
  {
    id: 'hogue-landscape-services',
    company: 'Hogue Landscape Services',
    industry: 'Landscaping',
    size: '20-60',
    location: 'Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 36000,
    priority: 'high',
    notes: '20+ years high-end landscapes'
  },
  {
    id: 'houston-landscape-pros',
    company: 'Houston Landscape Pros',
    industry: 'Landscaping',
    size: '15-45',
    location: 'Greater Houston, TX',
    painPoints: ["Needs assessment"],
    status: 'research',
    estimatedValue: 35500,
    priority: 'high',
    notes: 'Great team flexible reliable'
  }
]

// Summary statistics
export const leadStats = {
  total: 110,
  byStatus: {
    research: 110,
    outreach: 0,
    'call-scheduled': 0,
    proposal: 0,
    won: 0,
    lost: 0,
  },
  byIndustry: {
    "HVAC": 14,
    "Plumbing": 9,
    "Pest Control": 18,
    "Electrical": 6,
    "Multi-Service (HVAC/Plumbing/Electrical)": 4,
    "Pool Service": 4,
    "HVAC/Plumbing": 11,
    "Plumbing/HVAC": 3,
    "Multi-Service (Plumbing/HVAC/Electrical)": 1,
    "Multi-Service (Plumbing/HVAC)": 1,
    "Multi-Service (HVAC/Plumbing/Electrical/Roofing)": 1,
    "Multi-Service (Pest/HVAC/Lawn)": 1,
    "Roofing": 6,
    "Landscaping": 3,
    "Multi-Service": 11,
    "HVAC/Electrical": 1,
    "Commercial HVAC": 3,
    "Mechanical/Electrical/Plumbing": 1,
    "Multi-Service (HVAC/Plumbing)": 1,
    "Plumbing/HVAC/Electrical": 1,
    "HVAC/Plumbing/Electrical": 3,
    "Plumbing/Electrical/HVAC": 1,
    "HVAC/Electrical/Plumbing/Roofing": 1,
    "HVAC/Electrical/Plumbing": 1,
    "Pool Building": 1,
    "Fiberglass Pools": 1,
    "Pool Repair/Remodel": 1,
    "Commercial Pest Control": 1
  },
  totalValue: 4017000,
  avgValue: 36518
}
